apiVersion: v1
kind: Pod
metadata:
  name: conjur-auth-test
  namespace: default
spec:
  serviceAccountName: docker-demo-sa
  containers:
    - name: test
      image: curlimages/curl:latest
      command: ["sleep", "3600"]
      volumeMounts:
        - name: conjur-token
          mountPath: /var/run/secrets/conjur
          readOnly: true
  volumes:
    - name: conjur-token
      projected:
        sources:
          - serviceAccountToken:
              path: token
              expirationSeconds: 6000
              audience: "conjur"
  restartPolicy: Never
